services:
  # PostgreSQL Database Service
  dev-db:
    image: postgres:15
    ports:
      - '5434:5432'

    # NestJS Application Service
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=root

    networks:
      - freeCodeCamp

networks:
  freeCodeCamp:
